CREATE ROLE cvadmin WITH PASSWORD 'cvadmin' SUPERUSER CREATEDB LOGIN;
CREATE DATABASE cv;
\c cv
CREATE SCHEMA cv;
GRANT ALL PRIVILEGES ON SCHEMA cv TO postgres;
GRANT ALL PRIVILEGES ON SCHEMA cv TO cvadmin;
GRANT ALL PRIVILEGES ON DATABASE cv TO postgres;
GRANT ALL PRIVILEGES ON DATABASE cv TO cvadmin;


CREATE TABLE cv.stack (
    id SERIAL PRIMARY KEY,
    tier VARCHAR(100) NOT NULL,
    name VARCHAR(100) NOT NULL,
    product VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ;
